force-app/main/default/objects/List_Filter__c/List_Filter__c.object-meta.xml
<CustomObject>
    <label>List Filter</label>
    <nameField>
        <label>Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Filter__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <description>This filed is used for to add conditions, i.e Name = &apos;Any&apos; AND Email = &apos;con@te.com&apos;</description>
    <label>Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/List_Filter__c/fields/Condition_JSON__c.field-meta.xml
<CustomField>
    <fullName>Condition_JSON__c</fullName>
    <label>Condition JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/List_Filter__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this checked, then this filter shows as public</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Filter__c/fields/Screen_Name__c.field-meta.xml
<CustomField>
    <fullName>Screen_Name__c</fullName>
    <description>This fields is used for to identify component screen</description>
    <label>Screen Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ListFilterController.cls
public with sharing class ListFilterController {
    /**
     * @description getObjectFields : Fetch fields of object name with field type, label and api name
     * @param  objName objName : Object Name
     * @return         return : return Map of label with fields( type, label)
     */
    @AuraEnabled(cacheable=true)
    public static map<string, list<object>> getObjectFields(String objName) {
        map<string, list<object>> retVal = new Map<string, list<object>>();
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe()
            .get(objName)
            .getDescribe()
            .fields.getMap();
        for (String fieldName : fieldMap.keySet()) {
            string fieldType = String.ValueOf(
                fieldMap.get(fieldName).getDescribe().getType()
            );
            if (fieldType != 'TEXTAREA') {
                String fieldApi = fieldMap.get(fieldName)
                    .getDescribe()
                    .getName();
                List<String> listStrings = new List<String>();
                listStrings.add(fieldApi);
                listStrings.add(fieldType.toLowercase()); //Adding field type
                string fieldLabelName = fieldMap.get(fieldName)
                    .getDescribe()
                    .getLabel();
                retVal.put(fieldLabelName, listStrings);
            }
        }
        return retVal;
    }

    /**
     * @description fetchFilters : fetch filter that is created by user
     * @param  cmpName cmpName : component name of lwc with multiple screen
     * @return         return : Map<Id, List_Filter__c>
     */
    @AuraEnabled
    public static Map<Id, List_Filter__c> fetchFilters(String cmpName) {
        Id currentUser = userInfo.getUserId();
        return new Map<Id, List_Filter__c>(
            [
                SELECT
                    Id,
                    Name,
                    Condition__c,
                    Public__c,
                    Condition_JSON__c,
                    CreatedById,
                    CreatedBy.Name
                FROM List_Filter__c
                WHERE
                    (Screen_Name__c = :cmpName
                    AND CreatedById = :currentUser)
                    OR Public__c = TRUE
                WITH SECURITY_ENFORCED
            ]
        );
    }
    /**
     * @description insertFilter : insert list filter
     * @param  objFilter objFilter : List_Filter__c
     * @return           return : return inserted filter
     */
    @AuraEnabled
    public static List_Filter__c insertFilter(List_Filter__c objFilter) {
        try {
            insert objFilter;
            return objFilter;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}